### PR TITLE
added scalable logo files

### PR DESCRIPTION
**Pull request by existenzial**
Added adjustable and scalable logos:

- sketch
- svg

### CODE REVIEW

**Comment by jerdog** [comment]
Hey thanks for submitting this! Can you describe what it is you're trying to provide here? There is an issue with the svg file which I'll address directly

**Review by jerdog — CHANGES_REQUESTED** [review]
The text is way off center

image

**Comment by existenzial** [comment]
Hi there! I read your comment about "not knowing Illustrator" and wanted to provide you with an svg file that wasn't in the Pixelmator Pro extension and a Sketch file to mess around with to your liking. You'll probably need to keep messing with the text label end shapes to match the exact roundness of your logo, but this should get you started I hope.

**Comment by mbbroberg** [comment]
Hey @existenzial! This was very kind of you to send our way. I'll merge this and add it to an `/experimental` subfolder for follow up. Cheers 👍

**Pull request merged**
